import type { PropertyProps } from "@/interfaces";
export const SITE_NAME="StayNia";
export const SITE_TAGLINE="Find trusted stays across Kenya";
export const AMENITIES=["Wi-Fi","Parking","Kitchen","Pool","Workspace"] as const;
export const PROPERTY_TYPES=["Apartment","Cottage","Lodge","Villa"] as const;
// Canonical fictional fixtures. All listing facts are sample data.
export const PROPERTYLISTINGSAMPLE: PropertyProps[]=[
{id:"nairobi-garden-apartment",name:"Nairobi Garden Apartment",description:"A fictional city apartment fixture used to demonstrate StayNia's browsing experience.",address:{destination:"Nairobi",county:"Nairobi",country:"Kenya"},propertyType:"Apartment",rating:4.8,price:8500,bedrooms:2,bathrooms:2,maxGuests:4,amenities:["Wi-Fi","Parking","Kitchen","Workspace"],images:[{src:"/assets/md.avif",alt:"Temporary fixture image of a modern property exterior"},{src:"/assets/md2.webp",alt:"Temporary fixture image of a bright property exterior"}]},
{id:"diani-coast-villa",name:"Diani Coast Villa",description:"A fictional coastal villa fixture for exploring filters and quote estimates.",address:{destination:"Diani",county:"Kwale",country:"Kenya"},propertyType:"Villa",rating:4.9,price:18500,bedrooms:3,bathrooms:3,maxGuests:6,amenities:["Wi-Fi","Parking","Kitchen","Pool"],images:[{src:"/assets/m3.jpg",alt:"Temporary fixture image of a villa with a pool"},{src:"/assets/md3.webp",alt:"Temporary fixture image of a contemporary house"}]},
{id:"naivasha-lakeside-cottage",name:"Naivasha Lakeside Cottage",description:"A fictional cottage fixture representing a quiet weekend stay near Naivasha.",address:{destination:"Naivasha",county:"Nakuru",country:"Kenya"},propertyType:"Cottage",rating:4.6,price:12000,bedrooms:2,bathrooms:1,maxGuests:4,amenities:["Parking","Kitchen","Workspace"],images:[{src:"/assets/m2.jpg",alt:"Temporary fixture image of a modern cottage"},{src:"/assets/md4.webp",alt:"Temporary fixture image of a residential exterior"}]},
{id:"nanyuki-view-lodge",name:"Nanyuki View Lodge",description:"A fictional lodge fixture used to demonstrate a larger-group property page.",address:{destination:"Nanyuki",county:"Laikipia",country:"Kenya"},propertyType:"Lodge",rating:4.7,price:22000,bedrooms:4,bathrooms:3,maxGuests:8,amenities:["Wi-Fi","Parking","Kitchen"],images:[{src:"/assets/m4.jpg",alt:"Temporary fixture image of a spacious modern lodge"},{src:"/assets/md5.webp",alt:"Temporary fixture image of a landscaped property"}]},
{id:"watamu-breeze-villa",name:"Watamu Breeze Villa",description:"A fictional coastal fixture showing an amenity-rich villa for family groups.",address:{destination:"Watamu",county:"Kilifi",country:"Kenya"},propertyType:"Villa",rating:4.85,price:19500,bedrooms:3,bathrooms:2,maxGuests:6,amenities:["Wi-Fi","Parking","Kitchen","Pool","Workspace"],images:[{src:"/assets/m1.jpg",alt:"Temporary fixture image of a tropical-style property"},{src:"/assets/md2.webp",alt:"Temporary fixture image of a modern property exterior"}]},
{id:"kisumu-city-apartment",name:"Kisumu City Apartment",description:"A fictional apartment fixture representing a compact city stay in Kisumu.",address:{destination:"Kisumu",county:"Kisumu",country:"Kenya"},propertyType:"Apartment",rating:4.5,price:6500,bedrooms:1,bathrooms:1,maxGuests:2,amenities:["Wi-Fi","Kitchen","Workspace"],images:[{src:"/assets/md3.webp",alt:"Temporary fixture image of an apartment building"},{src:"/assets/md.avif",alt:"Temporary fixture image of a modern residential exterior"}]}
];
