import { AMENITIES,PROPERTY_TYPES } from "@/constants";
import type { Filters } from "@/lib/discovery";
export default function DiscoveryControls({value,onChange,onClear}:{value:Filters;onChange:(v:Filters)=>void;onClear:()=>void}){const set=(key:keyof Filters,v:string|string[])=>onChange({...value,[key]:v});return <section aria-labelledby="filters-title" className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 id="filters-title" className="text-lg font-bold">Search and filter</h2><button type="button" onClick={onClear} className="link-button">Clear filters</button></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
<label className="field">Destination or name<input value={value.q} onChange={e=>set("q",e.target.value)} type="search" placeholder="Try Diani"/></label>
<label className="field">Property type<select value={value.type} onChange={e=>set("type",e.target.value)}><option value="">All types</option>{PROPERTY_TYPES.map(x=><option key={x}>{x}</option>)}</select></label>
<label className="field">Minimum price (KES)<input value={value.minPrice} onChange={e=>set("minPrice",e.target.value)} min="0" type="number"/></label>
<label className="field">Maximum price (KES)<input value={value.maxPrice} onChange={e=>set("maxPrice",e.target.value)} min="0" type="number"/></label>
<label className="field">Guests<input value={value.guests} onChange={e=>set("guests",e.target.value)} min="1" type="number"/></label>
<label className="field">Minimum bedrooms<input value={value.bedrooms} onChange={e=>set("bedrooms",e.target.value)} min="1" type="number"/></label>
<label className="field">Sort by<select value={value.sort} onChange={e=>set("sort",e.target.value)}><option value="recommended">Recommended</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="rating">Sample rating</option></select></label>
</div><fieldset className="mt-4"><legend className="font-semibold">Amenities</legend><div className="mt-2 flex flex-wrap gap-3">{AMENITIES.map(a=><label key={a} className="inline-flex items-center gap-2"><input type="checkbox" checked={value.amenities.includes(a)} onChange={e=>set("amenities",e.target.checked?[...value.amenities,a]:value.amenities.filter(x=>x!==a))}/>{a}</label>)}</div></fieldset></section>}
